project:
  type: book
book:
  title: AI驱动Zotero智慧文献集成
  author: 文探007：张睿、兰聪、黄俊豪
  date: 2025/3/21
  chapters:
  - index.qmd
  
    
bibliography: references.bib
format:
  html:
    theme:
    - cosmo
    - brand
  pdf:
    documentclass: scrreprt
    include-in-header:
      text: '\usepackage{ctex}

        \usepackage{amsthm,mathrsfs}

        \usepackage{fvextra}

        \DefineVerbatimEnvironment{Highlighting}{Verbatim}{breaklines,commandchars=\\\{\}}

        '
editor: visual
