project:
  type: book

book:
  title: "AI"
  author: "Norah Jones"
  date: "2025/3/21"
  chapters:
    - index.qmd
    - intro.qmd
    - zetora.ipynb

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

