project:
  type: book

book:
  title: "文探：AI辅助文献筛选和批量解读平台"
  author: "文探007：张睿、兰聪、黄俊豪"
  date: "2025/3/21"
  chapters:
    - index.qmd
    - AI-Zotero.ipynb
    - file-fe-fQhUAzZa0hHekgRXwxPZIAjx.md
    - env.md
bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

