project:
  type: book

book:
  title: "AI给予的文献自动化管理系统"
  author: "张睿、兰聪、黄俊豪"
  date: "2025/3/21"
  chapters:
    - index.qmd
    - AI-Zetora.ipynb
    - AI解读结果.md
bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt

editor: visual

